### ISSUE TITLE
Need to `as.matrix()` before `BiocNeighbors::findKNN()`, etc. 

### ISSUE THREAD

**Issue by LTLA** [plger/scDblFinder#109]
I recently updated **BiocNeighbors** and one of the side effects of the change was that the various functions no longer automatically coerce their inputs to an ordinary matrix (to avoid headaches from S4 multiple dispatch ambiguity). The fix is straightforward, just `as.matrix()` the inputs to all functions, which should resolve the current build failures on the BBS.

It's worth mentioning that the previous version of **BiocNeighbors** did this coercion internally anyway, so there's no efficiency loss in that regard. Future versions of **BiocNeighbors** may provide direct support for non-ordinary matrices but this probably won't save all that much memory given that the built search indices eventually need to hold the data in dense format anyway.

**Comment by plger** [comment]
Many thanks for the easily-actionable tip...
