### ISSUE TITLE
Documentation and recommendations regarding the dbr parameter.

### ISSUE THREAD

**Issue by vertesy** [plger/scDblFinder#110]
Hey, thank you for the great package.

I suggest an improvement on the documentation / recommendations.

### You currently write:

> If you did not provide it (dbr argument), the doublet rate will be calculated automatically using expected doublet rates from 10x, meaning that the more cells captured, the higher the doublet rates. If you have reasons to think that this is not applicable to your data, set the dbr manually.
 
> ... 10X-like data tends to have roughly 1% per 1000 cells captured

### I suggest to mention:

- As per documentation, 10X _standard_ chips data has roughly 1% doublet rate increase per 1000 cells captured. 10X _High-Throughput_ chips the doublet rate is roughly half of that (used 2x inlets). As far as i know, their latest chip uses 4 inlets, so the expected doublet rate is 1/4 of standard chips. 

(I do not see enough data to validate 10X's claims, but makes sense.)

I do the estimate as:
```r
doublet_rate <- function(n.cells, instrument.factor = 1e5) n.cells / instrument.factor
doublet_rate(1e3)
doublet_rate(1e4)
```
where `instrument.factor` can be doublet for HT chips.

**Comment by plger** [comment]
Hi,
thanks for bringing this to my attention.
I've added a `dbr.per1k` argument (also changed the default 1% to 0.8%, had meant to do that for a while) and updated the documentation accordingly. Let me know if you think anything is unclear.
Pierre-Luc

**Comment by vertesy** [comment]
That's Great, Thank you!
