### ISSUE TITLE
Note to self: figure out why computeDoubletDensity is unhappy on R-devel

### ISSUE THREAD

**Issue by LTLA** [plger/scDblFinder#28]
Probably something to do with `I()`:

http://bioconductor.org/checkResults/devel/bioc-LATEST/scDblFinder/malbec2-checksrc.html

Also note the many other complaints in the CHECK report. Some of these are mine, some of these are for @plger.

**Comment by plger** [comment]
There's a couple of notes I got rid of (not pushed yet), otherwise relating to my stuff the only warning I see is the `'::' or ':::' imports not declared`, which I precisely didn't want to have as package dependencies...
Any idea why the error doesn't show up in the github action check?

**Comment by LTLA** [comment]
Regarding the imports, you can just stick them in the Suggests and they'll go away. I consider stuff in Suggests to not count towards my dependencies, as they aren't pulled down during install and they aren't loaded during `library()`.

> Any idea why the error doesn't show up in the github action check?

Probably because it's an R-devel thing, and we haven't re-triggered the action since the release. You'll notice that **scDblFinder** works just fine on BioC-release. I'm betting it's the change to the behavior to `I()`, I guess we'll find out now.
