### ISSUE TITLE
Size factors should be positive

### ISSUE THREAD

**Issue by Yale73** [plger/scDblFinder#32]
Hi scDblFinder team,

Thanks for such a great package. Recently, I am using this package to find the doublet cells for my Seurat object. I transferred my Seurat object into single cell experiment, but when I run the scDblFinder, I got an error: Size factors should be positive. My Seurat object has no log-transformation. But even after I log-transformed them, I still got the same error. I also have other datasets and they can run it smoothly. The only difference is the failed datasets have mouse cell spike-in, but I have removed these cells before running scDblFinder. Is there any solution for this issue?

Thanks,
Yale

**Comment by plger** [comment]
Hi,
The most likely explanation is that you have cells with a very low read count. Can you check `min(colSums(counts(SCE)))`, where SCE is your singlecellexperiment object?

**Comment by Yale73** [comment]
Hi @plger,

Thanks for your reply. You are absolutely right. I checked the failed ones, themin(colSums(counts(SCE))) is 0, while the successful ones are above 0. 

How can I change it?

Thanks,
Yale

**Comment by Yale73** [comment]
Hi @plger ,

Thanks for your reply. The failed ones have `min(colSums(counts(SCE)))` = 0. I ran the QC first and then the scDblFinder. Now they worked.

Thanks again,
Yale

**Comment by plger** [comment]
Added this to the FAQs.
Note that we recommend not filtering too much before running scDblFinder (but removing the droplets not containing cells).

**Comment by Yale73** [comment]
Hi @plger,

If you recommend not filtering too much, why not recommend us to run scDblFinder first and then filter the cells? As I found if I ran the scDblFinder first and then filter, I will keep a little more high-quality cells.


Object   with 4822 cells | Singlets | Doublets
-- | -- | --
First scDblFinder | 4558 | 264
Then filter | 4493 |  
  |   |  
First filter | 4717 |  
Then scDblFinder | 4475 | 242

Thanks,
Yale

**Comment by plger** [comment]
That's actually what I recommend (see for instance in the README, or in the pipeComp paper), however your earlier issue shows that some minimal filtering is needed to at least remove empty (or nearly empty) droplets...

**Comment by Yale73** [comment]
I see. I forget the filter is to remove the empty, If with empty, I will run the earlier issue.

Thanks,
Yale
