### ISSUE TITLE
Installing fails as requires R 4.1.0

### ISSUE THREAD

**Issue by JTpath** [plger/scDblFinder#35]
Trying to update gives the following error

`ERROR: this R is version 4.0.5, package 'scDblFinder' requires R >= 4.1
`

Isn't 4.1 still in development?

**Comment by plger** [comment]
Yes, they seem to be running late, but it's expected before the next Bioconductor release (3.13, on May 19th, might be delayed if R 4.1 still isn't out), so Bioconductor makes us to develop the next versions using R-devel. This isn't really required by scDblFinder though, so in the meantime I've created a branch with just 4.0 requirement, you can install using:

```
BiocManager::install("plger/scDblFinder", ref="R40")
```

**Comment by JTpath** [comment]
Works great! Thanks for all the hard work and the awesome tool
