### ISSUE TITLE
Error in ecdf(d$cxds_score[w]) : 'x' must have 1 or more non-missing values

### ISSUE THREAD

**Issue by lindsaynhayes** [plger/scDblFinder#37]
I have 18 samples constructed as a list of 18 SCE objects in which I performed `emptyDrops()` and `scDblFinder()` in loops. One of the samples (loop 11) failed at the `scDblFinder()` step with the error `"Error in ecdf(d$cxds_score[w]) : 'x' must have 1 or more non-missing values"`. I know the scripts are working because the other 17 worked so I'm not sure what is wrong with that one object since it was constructed the same as all others that is causing this error. I found the line I think is hanging up `2*ecdf(d$cxds_score[w])(d$cxds_score[w])` in the command, but I don't know how to fix my file. 

I reran all the scripts again thinking maybe something didn't get saved in-between correctly on the HPC, but same error same spot. 

**Update: if I run `use.cxds = FALSE` it finishes. I'm still uncertain why this one SCE object has this problem.** 

```
Samples = list.files(path='./mats')
for(i in Samples){
RawDat[[i]] <- read10xCounts(paste("/PATH/RAW/mats",i,sep='/'))
cat(paste(i,', ',sep=''))
}

emp_out = vector(mode='list',length=length(Samples))
names(emp_out) = Samples
for(i in Samples){
emp_out[[i]] <- emptyDrops(counts(RawDat[[i]]))
cat(paste(i,', ',sep=''))
}

CellDat = vector(mode='list',length=length(Samples))
names(CellDat) = Samples
for(i in Samples){
CellDat[[i]] <- RawDat[[i]][,which(emp_out[[i]]$FDR <= 0.001)]
cat(paste(i,', ',sep=''))
}

set.seed(101)
for(i in Samples){ 
CellDat[[i]] <- scDblFinder(CellDat[[i]])
cat(paste(i,', ',sep=''))
}

# ERROR at loop 11 (1-10 and 12 - 18 finishes)
Clustering cells...
11 clusters
Creating ~8883 artifical doublets...
Dimensional reduction
Finding KNN...
Evaluating cell neighborhoods...
Training model...
Error in ecdf(d$cxds_score[w]) : 'x' must have 1 or more non-missing values

> CellDat[[11]]
class: SingleCellExperiment 
dim: 32285 14805 
metadata(1): Samples
assays(1): counts
rownames(32285): ENSMUSG00000051951 ENSMUSG00000089699 ...
  ENSMUSG00000095019 ENSMUSG00000095041
rowData names(3): ID Symbol Type
colnames: NULL
colData names(2): Sample Barcode
reducedDimNames(0):
altExpNames(0):

> CellDat[[12]]
class: SingleCellExperiment 
dim: 32285 2131 
metadata(2): Samples scDblFinder.stats
assays(1): counts
rownames(32285): ENSMUSG00000051951 ENSMUSG00000089699 ...
  ENSMUSG00000095019 ENSMUSG00000095041
rowData names(4): ID Symbol Type scDblFinder.selected
colnames(2131): cell1 cell2 ... cell2130 cell2131
colData names(12): Sample Barcode ... scDblFinder.mostLikelyOrigin
  scDblFinder.originAmbiguous
reducedDimNames(0):
altExpNames(0):

```

**Comment by plger** [comment]
Hi,
please report the version of the package you're using (in general it's always good to include a `sessionInfo()` with bug reports). I suspect you're using an old version.
Your object 11 doesn't have colnames; in older versions this could cause a problem.
If that's not your issue, please run the sample outside the loop and report the output of `traceback()` after the error.

**Comment by lindsaynhayes** [comment]
Thanks!
1. I am running `scDblFinder_1.4.0` both on HPC and locally. 
2. I ran 11 locally by itself and still got the same error at the same spot. Here is session info for locally. 
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ensembldb_2.14.1            AnnotationFilter_1.14.0     GenomicFeatures_1.42.3     
 [4] AnnotationDbi_1.52.0        AnnotationHub_2.22.1        BiocFileCache_1.14.0       
 [7] dbplyr_2.1.1                scDblFinder_1.4.0           DropletUtils_1.10.3        
[10] SingleCellExperiment_1.12.0 SummarizedExperiment_1.20.0 Biobase_2.50.0             
[13] GenomicRanges_1.42.0        GenomeInfoDb_1.26.7         IRanges_2.24.1             
[16] S4Vectors_0.28.1            BiocGenerics_0.36.1         MatrixGenerics_1.2.1       
[19] matrixStats_0.58.0         
```
3. Here is session info for HPC (I'm running under a conda environment to load packages)
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /home-net/home-3/lhayes14@jhu.edu/code/environ/env-10X/lib/libopenblasp-r0.3.10.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] scDblFinder_1.4.0           DropletUtils_1.10.3        
 [3] SingleCellExperiment_1.12.0 SummarizedExperiment_1.20.0
 [5] Biobase_2.50.0              GenomicRanges_1.42.0       
 [7] GenomeInfoDb_1.26.4         IRanges_2.24.1             
 [9] S4Vectors_0.28.1            BiocGenerics_0.36.0        
[11] MatrixGenerics_1.2.1        matrixStats_0.58.0     
```
4. Here is the Traceback.
```
> traceback()
4: stop("'x' must have 1 or more non-missing values")
3: ecdf(d$cxds_score[w])
2: .scDblscore(cbind(d, pca[, includePCs, drop = FALSE]), scoreType = score, 
       threshold = threshold, dbr = dbr, dbr.sd = dbr.sd, nrounds = nrounds, 
       max_depth = max_depth, iter = iter, BPPARAM = BPPARAM, verbose = verbose, 
       metric = metric)
1: scDblFinder(CellDat_11)
```

**Comment by plger** [comment]
Thanks for the details.
As a control, could you report the output of `table(is.na(cxds2(counts(sce))))` ?
You could try if the problem persists in the development version (install with `BiocManager::install("plger/scDblFinder", ref="R40")` ).

**Comment by lindsaynhayes** [comment]
Strange...
```
> table(is.na(cxds2(counts(CellDat_11A))))

FALSE 
14017
```

Is there a negative consequence of running with `use.cxds = FALSE` does that dramatically change what it calls as singlet vs doublet? It look reasonable to me when I plot.

**Comment by plger** [comment]
No, it's just information that's very cheap to get and include, but the overall impact is marginal, really. You can safely go ahead with `use.cxds=FALSE`. This being said, I'd personally like to understand what's happening and prevent the error from occurring in the future... Could you maybe share the SCE object (you could keep only the top 1000 most expressed genes to make it smaller, and if you're concerned about the data you can rename genes and columns)?

**Comment by lindsaynhayes** [comment]
[cxdsErr.zip](https://github.com/plger/scDblFinder/files/6385514/cxdsErr.zip)

**Comment by plger** [comment]
Thanks!
So the problem is due to some cells that have an extremely low library size: you've got cells with just 42 reads! These are rather unlikely to bring you more than trouble, and if you filter them out (e.g. `sce <- sce[,colSums(counts(sce))>200]`), things should work fine.
I'll be adding appropriate warnings to prevent cryptic error messages, though.

**Comment by lindsaynhayes** [comment]
Great, thanks! Those are probably empty droplets. The `emptyDrops` maybe isn't catching those as well as the 10X default filtering. In any case, yes I will filter them out.

**Comment by LTLA** [comment]
FYI `emptyDrops` wouldn't report anything with fewer than 100 UMIs, unless you set `lower=` to something lower.
