### ISSUE TITLE
Pre-filter the count matrix before scDblFinder?

### ISSUE THREAD

**Issue by merckey** [plger/scDblFinder#40]
Dear Developers,
I'm including this awesome tool in my scRNA-seq analysis workflow but hope you could help clarify the correct procedures.

I notices that in the github readme page, the function takes the count matrix without empty cells as input. My question is, do I need to perform the regular filters (such as lower/upper thresholds for the number of genes per cell or the total UMI counts per cell) before I feed the data to scDblFinder? I saw people doing different things, but think may double-check with you.

Thanks,
Jp

**Comment by plger** [comment]
Hi,
assuming that cells/droplets with very low counts (e.g. <200) are excluded, it should not be necessary to perform filtering before running scDblFinder. However, there are two reasons that speak in favor of doing doublet detection first, and QC filtering after:
1. the default expected doublet rate is calculated on the basis of the cells given, and if you excluded a lot of cells as low quality, scDblFinder might think that the doublet rate should be lower than it is.
2. kicking out all low quality cells first might hamper our ability to detect doublets that are formed by the combination of a good quality cell with a low-quality one.
For these reasons, we generally run scDblFinder first. This being said, these ground are mostly theoretical; unless your QC filtering is very stringent (and it shouldn't be!), it's unlikely to make a big difference.
(Thanks for the question, will add this to FAQs)
Pierre-Luc

**Comment by merckey** [comment]
Thank you so much for the clarification!
I think the recommended procedure makes a lot of sense.
Jp
