### ISSUE TITLE
Issue with knownDoublets

### ISSUE THREAD

**Issue by bjstewart1** [plger/scDblFinder#45]
the knownDoublets option in `scDblFinder` is is throwing an error when presented with `knownDoublets` and also `samples`

Reproducible example:
```
library(scDblFinder)
sce <- mockDoubletSCE()
sce$type <- sce$type %in% "doublet"
sce$channel <- c(rep("sample1", floor(ncol(sce)/2)), rep("sample2", ceiling(ncol(sce)/2)))[1:ncol(sce)]
scldbl <- scDblFinder(sce = sce, 
                      samples = "channel",
                      knownDoublets = "type")


```

yields
`
Error in value[[3L]](cond) :    An error occured while processing sample 'cluster1': Error in .checkColArg(sce, knownDoublets): `knownDoublets` should have a length equal to the number of columns in `sce`.
`

but 

```
scldbl <- scDblFinder(sce = sce, 
                      #samples = "channel",
                      knownDoublets = "type")


```
succeeds
`Clustering cells... 4 clusters Creating ~5000 artifical doublets... Dimensional reduction Finding KNN... Evaluating cell neighborhoods... Training model... Finding threshold... Threshold found:0.425 19 (3.7%) doublets called`

**Comment by plger** [comment]
thanks, will look into it in the next couple of days. I'm assuming you're using the latest github version?
Note that the current usage of knownDoublets actually decreases performance if (as is often the case) a sizeable fraction of the known doublets are homotypic. More flexibility on their usage will be added soon.

**Comment by bjstewart1** [comment]
yes this is after 
`BiocManager::install("plger/scDblFinder")`
on 19-7-21
thanks

**Comment by plger** [comment]
should be fixed in the latest push
