### ISSUE TITLE
Forgot to import sweep from DelayedArray

### ISSUE THREAD

**Issue by LTLA** [plger/scDblFinder#49]
Oops:

```r
library(scDblFinder)
example(computeDoubletDensity, echo=FALSE)
library(DelayedArray)
scores <- computeDoubletDensity(DelayedArray(counts))
## Error in .check_Ops_vector_arg_length(e, x_nrow, e_what = e_what, x_what = x_what) :
##   when the right operand is not a DelayedArray object (or derivative),
##   its length (250000) cannot be greater than the first dimension of the
##   left operand (10000)
```

Should be a very simple matter of slapping `@importFrom DelayedArray sweep` on top of `.spawn_doublet_pcs()`. Still spawns a warning but I think that's a **DelayedArray** problem rather than anything on our end.

**Comment by plger** [comment]
Do you want me to do it or you do?
This makes me think that I still have to make the scDblFinder method compatible with DelayedArray (i.e. without conversion to a sparseMatrix)...

**Comment by LTLA** [comment]
> Do you want me to do it or you do?

Could you do it? Would save me having to create a PR. I always forget whether I have write access to this repo.

> This makes me think that I still have to make the scDblFinder method compatible with DelayedArray (i.e. without conversion to a sparseMatrix)...

There's a couple of lessons learnt from **scran** and **DropletUtils** and friends:

- If you're doing multiple passes over the input matrix, it's better to (by default) convert any input delayed array into a more convenient format (e.g., `dgCMatrix`) up front, otherwise you'll be wasting a lot of time in block processing.
- However, this also comes at the obvious cost of increasing memory usage. So the ideal situation is when you only need a subset of features (e.g., HVGs) or cells, in which case you can subset and convert without blowing up your RAM.
- Of course, if you're just doing one pass over the matrix, the cost of block processing is about equal to the cost of the conversion anyway, so you might as well just keep it in the delayed array format.

There are exceptions to this rule for the fancier DelayedMatrices that have specialized operators (e.g., `ResidualMatrix` and `ScaledMatrix` for efficient matrix multiplication) that are more efficient than what you could get from a converted matrix.

**Comment by plger** [comment]
done for sweep... will push to bioc after the auto check.
Thanks for the tips. I think I'll do it right after the subsetting then.
