### ISSUE TITLE
Issue running scDblFinder on scATAC-seq data

### ISSUE THREAD

**Issue by debbie28** [plger/scDblFinder#51]
Hello,

I am trying to run scDblFinder to find doublets in my scATAC-seq data but run into the following error early on:

Error in names(res) <- nms : 
  'names' attribute [4] must be the same length as the vector [2]
In addition: Warning message:
stop worker failed:
  attempt to select less than one element in OneIndex

From preliminary google searches, this problem seems external to scDblFinder, but any insight you may have will be very helpful.
 I am running the following code:

cancer_2_h_new
#An object of class Seurat 
#251195 features across 23665 samples within 1 assay 
#Active assay: ATAC (251195 features, 251195 variable features)
#4 dimensional reductions calculated: lsi, umap, harmony, umap_harmony

cancer_sce = as.SingleCellExperiment(cancer_2_h_new)

set.seed(123)
library(scDblFinder)
library(BiocParallel)

sce <- scDblFinder(cancer_sce, samples="Mouse", aggregateFeatures=TRUE, nfeatures=25,BPPARAM=MulticoreParam(3), processing = "normFeatures")

**Comment by plger** [comment]
Hi,
Thanks for reporting, but please always include the package version with issues!
With multi-threading we won't get very useful error msgs, so could you run it without the `BPPARAM` argument?  Assuming you still encounter the error, use `traceback()` right after to get its trace.
Pierre-Luc

**Comment by LTLA** [comment]
Usually this kind of cryptic error means that you ran out of memory on one of the worker processes. On my systems, I often observe this because the OS will kill individual workers when R exceeds the allocated memory; this means that some workers will finish and others won't, leading to weird errors like this.

**Comment by plger** [comment]
@debbie28 , will close this issue unless you want to follow up on it.
