### ISSUE TITLE
why error ?

### ISSUE THREAD

**Issue by kdyoung100** [plger/scDblFinder#56]
bcmvn.MM482 <- find.pK(sweep.stats.MM482)
DimPlot(object = MM482.BM, reduction = 'umap', group.by = "RNA_snn_res.0.5", label = TRUE, repel = TRUE, raster=FALSE) + NoLegend()
FeaturePlot(MM482.BM, features = "scDblFinder.score", cols = c("yellow", "red"), reduction = 'umap', raster = FALSE) + DarkTheme()
FeaturePlot(MM482.BM, features = "pANN_0.25_0.005_555",cols = c("yellow", "red"), reduction = 'umap', raster=FALSE) + DarkTheme()
DimPlot(MM482.BM,pt.size = 1,label=FALSE, label.size = 5,reduction = "umap",group.by = "DF.classifications_0.25_0.005_555")
DimPlot(MM482.BM,pt.size = 1,label=FALSE, label.size = 5,reduction = "umap",group.by = "DF.classifications_0.25_0.005_483")
MM482.BM <- doubletFinder_v3(MM482.BM, PCs = use.pcs, pN = 0.25, pK = mpk.MM482, nExp = nExp_poi.adj.MM482, reuse.pANN = "pANN_0.25_0.005_555", sct = FALSE)
MM482.singlet <- subset(x = MM482.BM, subset = DF.classifications_0.25_0.005_483 == "Singlet")
MM482.singlet

FeaturePlot(MM482.BM, features = "scDblFinder.score", cols = c("yellow", "red"), reduction = 'umap', raster = FALSE) + DarkTheme()
Error: None of the requested features were found: scDblFinder.score in slot data
In addition: Warning message:
In FetchData(object = object, vars = c(dims, "ident", features),  :
  The following requested variables were not found: scDblFinder.score

**Comment by kdyoung100** [comment]
bcmvn.MM625 <- find.pK(sweep.stats.MM625)
DimPlot(object = MM625.BM, reduction = 'umap', group.by = "RNA_snn_res.0.5", label = TRUE, repel = TRUE, raster=FALSE) + NoLegend()
FeaturePlot(MM625.BM, features = "pANN_0.25_0.005_389",cols = c("yellow", "red"), reduction = 'umap', raster=FALSE) + DarkTheme()
MM625.BM <- doubletFinder_v3(MM625.BM, PCs = use.pcs, pN = 0.25, pK = mpk.MM625, nExp = nExp_poi.adj.MM625, reuse.pANN = "pANN_0.25_0.005_389", sct = FALSE)
DimPlot(MM625.BM, pt.size = 1, label = FALSE, label.size = 5, reduction = "umap", group.by = "scDblFinder.class")
DimPlot(MM625.BM,pt.size = 1,label=FALSE, label.size = 5,reduction = "umap",group.by = "DF.classifications_0.25_0.005_389")
DimPlot(MM625.BM,pt.size = 1,label=FALSE, label.size = 5,reduction = "umap",group.by = "DF.classifications_0.25_0.005_352")
MM625.singlet <- subset(x = MM625.BM, subset = DF.classifications_0.25_0.005_352 == "Singlet")
MM625.singlet
Error: Cannot find 'scDblFinder.class' in this Seurat object 
 why error?

**Comment by kdyoung100** [comment]
bcmvn.MM800 <- find.pK(sweep.stats.MM800)
DimPlot(object = MM800.BM, reduction = 'umap', group.by = "RNA_snn_res.0.5", label = TRUE, repel = TRUE, raster=FALSE) + NoLegend()
FeaturePlot(MM800.BM, features = "pANN_0.25_0.19_329",cols = c("yellow", "red"), reduction = 'umap', raster=FALSE) + DarkTheme()
MM800.BM <- doubletFinder_v3(MM800.BM, PCs = use.pcs, pN = 0.25, pK = mpk.MM800, nExp = nExp_poi.adj.MM800, reuse.pANN = "pANN_0.25_0.19_329", sct = FALSE)
DimPlot(MM800.BM, pt.size = 1, label = FALSE, label.size = 5, reduction = "umap", group.by = "scDblFinder.class")
DimPlot(MM800.BM,pt.size = 1,label=FALSE, label.size = 5,reduction = "umap",group.by = "DF.classifications_0.25_0.19_329")
DimPlot(MM800.BM,pt.size = 1,label=FALSE, label.size = 5,reduction = "umap",group.by = "DF.classifications_0.25_0.19_293")
MM800.singlet <- subset(x = MM800.BM, subset = DF.classifications_0.25_0.19_293 == "Singlet")
MM800.singlet
Error: None of the requested features were found: pANN_0.25_0.19_329 in slot data
In addition: Warning message:
In FetchData(object = object, vars = c(dims, "ident", features),  :
  The following requested variables were not found: pANN_0.25_0.19_329
> MM800.BM <- doubletFinder_v3(MM800.BM, PCs = use.pcs, pN = 0.25, pK = mpk.MM800, nExp = nExp_poi.adj.MM800, reuse.pANN = "pANN_0.25_0.19_329", sct = FALSE)
Error in `[.data.frame`(seu@meta.data, , reuse.pANN) : 
  정의하지 않은 열들이 선택되었습니다
> DimPlot(MM800.BM, pt.size = 1, label = FALSE, label.size = 5, reduction = "umap", group.by = "scDblFinder.class")
Error: Cannot find 'scDblFinder.class' in this Seurat object
> DimPlot(MM800.BM,pt.size = 1,label=FALSE, label.size = 5,reduction = "umap",group.by = "DF.classifications_0.25_0.19_329")
Error: Cannot find 'DF.classifications_0.25_0.19_329' in this Seurat object
> DimPlot(MM800.BM,pt.size = 1,label=FALSE, label.size = 5,reduction = "umap",group.by = "DF.classifications_0.25_0.19_293")
Error: Cannot find 'DF.classifications_0.25_0.19_293' in this Seurat object
> MM800.singlet <- subset(x = MM800.BM, subset = DF.classifications_0.25_0.19_293 == "Singlet")
Error in FetchData(object = object, vars = unique(x = expr.char[vars.use]),  : 
  None of the requested variables were found: 
> MM800.singlet
Error: object 'MM800.singlet' not found

why error??

**Comment by kdyoung100** [comment]
bcmvn.MM482 <- find.pK(sweep.stats.MM482)
DimPlot(object = MM482.BM, reduction = 'umap', group.by = "RNA_snn_res.0.5", label = TRUE, repel = TRUE, raster=FALSE) + NoLegend()
FeaturePlot(MM482.BM, features = "scDblFinder.score", cols = c("yellow", "red"), reduction = 'umap', raster = FALSE) + DarkTheme()
FeaturePlot(MM482.BM, features = "pANN_0.25_0.005_555",cols = c("yellow", "red"), reduction = 'umap', raster=FALSE) + DarkTheme()
DimPlot(MM482.BM,pt.size = 1,label=FALSE, label.size = 5,reduction = "umap",group.by = "DF.classifications_0.25_0.005_555")
DimPlot(MM482.BM,pt.size = 1,label=FALSE, label.size = 5,reduction = "umap",group.by = "DF.classifications_0.25_0.005_483")
MM482.BM <- doubletFinder_v3(MM482.BM, PCs = use.pcs, pN = 0.25, pK = mpk.MM482, nExp = nExp_poi.adj.MM482, reuse.pANN = "pANN_0.25_0.005_555", sct = FALSE)
MM482.singlet <- subset(x = MM482.BM, subset = DF.classifications_0.25_0.005_483 == "Singlet")
MM482.singlet

FeaturePlot(MM482.BM, features = "scDblFinder.score", cols = c("yellow", "red"), reduction = 'umap', raster = FALSE) + DarkTheme()
Error: None of the requested features were found: scDblFinder.score in slot data
In addition: Warning message:
In FetchData(object = object, vars = c(dims, "ident", features),  :
  The following requested variables were not found: scDblFinder.score

**Comment by plger** [comment]
If you want help, you should try to make a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) rather than copy-pasting random chunks of mixed code and outputs. In this case the commands you run appear to be from the [DoubletFinder](https://github.com/chris-mcginnis-ucsf/DoubletFinder) package, so I'm not sure what you're doing here. If you want to run scDblFinder, please look at the documentation.
