### ISSUE TITLE
Possible Bug: cxds2 call does not include artificial doublets in whichDbls

### ISSUE THREAD

**Issue by alexvpickering** [plger/scDblFinder#57]
Here is where `cxds2` is being called:

https://github.com/plger/scDblFinder/blob/30090a000522379a96c44cfeefa6c75147160417/R/scDblFinder.R#L406

Here is an example `ctype` that I came across (assigned just above):

```R
# dimensions of various things
ncol_sce <- 26657
len_wDbl <- 0
ncol_ad <- 21325
knownUse <- 'discard'

# using above dimensions to make ctype
ctype_bad <- factor(
  rep(
    c(1L, ifelse(knownUse=="positive", 2L, 1L), 2L),
    c(ncol_sce, len_wDbl, ncol_ad), 
    ),
  labels = c("real", "doublet")
)

# ctype looks reasonable
table(ctype_bad)
#ctype_bad
#   real doublet 
#  26657   21325

# given above, and call to cxds2: artificial doublets not added to whichDbls
which(ctype_bad == 2L)
# integer(0)
```

Just wondering if this is a bug or intentional. Thanks!

**Comment by plger** [comment]
you're absolutely right, this was wrong and embarrassing, thanks a lot for pointing it out. I've corrected it now and will push back to the BioC release as soon as the checks have passed.
