### ISSUE TITLE
Error in scDblFinder() due to NULL `th`

### ISSUE THREAD

**Issue by ansonrel** [plger/scDblFinder#6]
Hi, 

Trying the function on the `Kumar` dataset I got : 

```
> scDblFinder(sce, trans = "scran", verbose=FALSE)
Error in `$<-.data.frame`(`*tmp*`, "classification", value = logical(0)) : 
  replacement has 0 rows, data has 457

```

Debugging a bit the function I noticed that `doubletThresholding()` returns `NULL` which causes the error with the empty values at this line in the code of `scDblFinder` ; 

`d$classification <- ifelse(d$ratio >= th, "doublet", "singlet")` 

Given that `th` is `NULL`.

**Comment by plger** [comment]
Hi,
If I'm not mistaken you're using an old version of the package. See the [readme](https://github.com/plger/scDblFinder) for installation of an up-to-date one.
Thanks,
Pierre-Luc
