### ISSUE TITLE
How to find all features used in training

### ISSUE THREAD

**Issue by XinyeZhao** [plger/scDblFinder#61]
Hi scDblFinder team!

It's mentioned in the paper that scDblFinder utilizes multiple features obtained from the Knn network, such as projections on principal components; library size; the number of detected features; and co-expression scores. But I can only find the scDblFinder.weighted and scDblFinder.cxds_score in the output R object. Could you tell me how to obtain all features used in training GDBT tree in the R object?

Thanks

**Comment by plger** [comment]
Hi,
if you use `retType="table"`, the output will be a data.frame containing all the variables for both real cells and artificial doublets.
Pierre-Luc
