### ISSUE TITLE
Merging multiple samples with scATAC prior to scDblFinder

### ISSUE THREAD

**Issue by rauldiul** [plger/scDblFinder#68]
Hi! Thanks for your great software.

I am using your package with some Multiome data (calling doublets separately for RNA and ATAC). I have multiple samples and was following your recommendation of creating a `SingleCellExperiment` with all samples together. This is straightforward for the RNA data (they all quantify the same rows/genes), but for the ATAC data, peaks/rows are unique for each library. I could do a merge of the ATAC peaks for each sample, and re-quantify in those regions (e.g. like [this](https://stuartlab.org/signac/articles/merging.html)), but it seems like a lot of pre-processing and modifying the raw count data prior to running the doublet finder algorithm.

So, what I'm asking is, how preferable is it to merge samples instead of doing the doublet finding separately per each sample? If results are (more or less) robust, maybe it is OK to run the samples separately?

thanks for your help

**Comment by plger** [comment]
Hi,
It's perfectly okay to call doublets in samples separately, in fact I couldn't measure a reproducible improvement coming form the merged processing/analysis, and most with default settings this is anyway what's happening (except that if a global PCA is present, it's going to be used).
Pierre-Luc

**Comment by rauldiul** [comment]
Great! Thanks!!
