### ISSUE TITLE
Return threshold in output?

### ISSUE THREAD

**Issue by maryellenlynall** [plger/scDblFinder#71]
Would it be possible to return the doublet threshold as part of the standard output, rather than only printing to console, so that it can be used programatically?
The full output becomes very unwieldy with an R environment with multiple large datasets so it would be v helpful to have this as a standard output to help interpret the doublet scores in the output.

**Comment by maryellenlynall** [comment]
Thanks!

**Comment by plger** [comment]
(fyi I had introduced a mistake through a typo in the same time, just pushed the fixed version now)

**Comment by maryellenlynall** [comment]
Many thanks!
