### ISSUE TITLE
I'm having an issues with sctransform  not sure 

### ISSUE THREAD

**Issue by zvan14** [plger/scDblFinder#74]
I'm somewhat new to using this so I am not sure how to fix it.
> Org_nodoub <- processing_seurat_sctransform(Org_nodoub,
                                                 vars_to_regress = c("nCount_RNA","percent.mito","percent.ribo"),
                                                 npcs = 30,
                                                 res = 0.5)
Error in qr.resid(qr = qr, y = data.expr[x, ]) :
  'qr' and 'y' must have the same number of rows

**Comment by plger** [comment]
This repo is neither about seurat nor sctransform, and I've never heard of `processing_seurat_sctransform`. You probably want to talk to whoever wrote that wrapper function.
