### ISSUE TITLE
Error when running library(scDblFinder) on jupyter through %%R

### ISSUE THREAD

**Issue by ngvananh2508** [plger/scDblFinder#77]
**Describe the bug**
When I ran library(scDblFinder) on jupyter, it appeared this error: Error: package or namespace load failed for ‘scDblFinder’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/nguyen/R/x86_64-pc-linux-gnu-library/4.1/xgboost/libs/xgboost.so':
  /home/nguyen/anaconda3/lib/python3.10/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/nguyen/R/x86_64-pc-linux-gnu-library/4.1/xgboost/libs/xgboost.so)
I tried to update libstdc++.so.6 and remove/install again but it can not work.
Please help me.
I am using R version 4.1.2 
I set up scDblFinder through BiocManager: version 1.13.13
Thank you very much.

**Comment by plger** [comment]
Hi,
This is not a problem of scDblFinder but of your `xgboost` installation. Try to google in this direction, for most people it seems something simple like installing libgcc and re-installing xgboost seems to work (e.g. [here](https://github.com/dmlc/xgboost/issues/1700)).

**Comment by ngvananh2508** [comment]
Thank you very much!
