### ISSUE TITLE
package ‘scDblFinder’ is not available (for R version 3.6.0) ???

### ISSUE THREAD

**Issue by linwang6** [plger/scDblFinder#8]
Hi, thanks for developing this cool tool.
When I try to install it in R 3.6.0 using "BiocManager::install("scDblFinder")" , it says "package ‘scDblFinder’ is not available (for R version 3.6.0)". 

Could you give any advice? Thanks.

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("scDblFinder")

**Comment by plger** [comment]
Hi,

what Bioconductor version are you using? i.e. `BiocManager::version()` ?

The package is in bioconductor only since BioC 3.10. You should be able to install on previous versions using `BiocManager::install("plger/scDblFinder")`, but I can't guarantee that everything will work properly (depends on whether the other packages on which it depends changed since then).

**Comment by linwang6** [comment]
> BiocManager::version()
[1] ‘3.9’

When I try "BiocManager::install("plger/scDblFinder")"

it gives:

** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
**Error: object ‘computeLibraryFactors’ is not exported by 'namespace:scater'
Execution halted
ERROR: lazy loading failed for package ‘scDblFinder’**
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/scDblFinder’
Error: Failed to install 'scDblFinder' from GitHub:
  (converted from warning) installation of package ‘/var/folders/dv/ybmb0fss0bgg7q577nbg39hr0000gn/T//RtmpexBNiJ/filec4d0355236ae/scDblFinder_1.1.11.tar.gz’ had non-zero exit status

**Comment by linwang6** [comment]
I will update BioC3.9 to BioC3.10

**Comment by plger** [comment]
Right, so `scater` for instance did change since 3.9...
I'm afraid you'll have to upgrade BioC.

**Comment by linwang6** [comment]
Thanks.
