### ISSUE TITLE
Running into Grid Error when Running scDblFinder

### ISSUE THREAD

**Issue by Sandman-1** [plger/scDblFinder#81]
Hello! I seem to be running into the following error when running scDblFinder on a single cell experiment atac object derived from a Seurat/Signac object. I have tried eliminating the dims, npcs, and k arguments, setting the processing mode to normFeatures as shown in the vignette, and reducing the number of maximum artificial doublets. They all give me the same error, though. Here is the code I used, followed by the error.

Code:
TCF7L2_filt <- readRDS("Seurat Objects/TCF7L2 with Called Peaks.rds")
TCF7L2_filt_sce_ATAC <- as.SingleCellExperiment(TCF7L2_filt, assay = "Peaks")
TCF7L2_filt_sce_ATAC@int_colData@listData[["reducedDims"]]@listData[["PCA"]] <- TCF7L2_filt_sce_ATAC@int_colData@listData[["reducedDims"]]@listData[["LSI"]]
TCF7L2_filt_sce_ATAC@int_colData@listData[["reducedDims"]]@listData[["LSI"]] <- NULL
TCF7L2_filt_sce_ATAC <- scDblFinder(TCF7L2_filt_sce_ATAC, clusters = TCF7L2_filt_sce_ATAC$seurat_clusters, Samples = TCF7L2_filt_sce_ATAC$Sample, aggregateFeatures = TRUE, dims = 50, includePCs = 2:40, k = 20, artificialDoublets = ncol(TCF7L2_filt))

Output:
Aggregating features...
Error in set_grid_context(X[[1]], X[[2]]) : 
  argument "current_viewport" is missing, with no default

**Comment by PeteHaitch** [comment]
I think you need to upgrade your Bioconductor installation to the latest version of **DelayedArray** (context: https://github.com/Bioconductor/DelayedArray/issues/104).
You can do this with `BiocManager::install()`.

After upgrading, restart R and try the code again.
If that doesn't help, please provide the output of `BiocManager::valid()`.

**Comment by plger** [comment]
(Thanks Peter)
@Sandman-1 can you confirm that this solved your problem?
